### PR TITLE
first notes on sort problem

### LINKED ISSUE #21: Incorrect work of QuerySort
SDK 4.2.10-beta

I just created a screen with channels and use the next code:
```
    val filter = Filters.and(Filters.`in`("members", userId))
    val querySort = QuerySort().desc("last_message_at")
    channelsViewModel?.setQuery(filter, querySort)
```
As a result, I got all necessary channels but with unexpected sorting.

### PR DESCRIPTION
**Pull request by tschellenbach**
Depend on https://github.com/GetStream/stream-chat-android-client/pull/110

Fix #21 

the sort changes between online and offline query. this is caused by the offline sort not working. 

see this video for clarification: https://www.loom.com/share/d956c3cb4353480ba9c321a9d026de0d

I investigated it a little bit, few issues:

1. - the backend uses field names like created_at which on the channel object are called createdAt, these don't match
2. - the default ordering is last_updated which is actually a composite field based on max(createdAt, lastMessageAt)
3. - you can receive new channels via an event. the current sort implementation is not applied after receiving an event. it's only used for the offline version of the channels.

I added a failing test for the first 2 issues.

1. - i added a fix for this. number 3 is also easy to solve by changing that Transform where I added a comment.

supporting last_updated is a bit harder, any ideas?

- maybe an extension function on the Channel object?

### CODE REVIEW

File: livedata/src/test/java/io/getstream/chat/android/livedata/PaginationTest.kt [hunk 1]
```diff
@@ -18,7 +19,9 @@ class PaginationTest {
         pagination: AnyChannelPaginationRequest,
         expectedList: List<ChannelEntityPair>
     ) {
-        inputList.applyPagination(pagination) `should be equal to` expectedList
+        // show an easy to use diff between the two results
```
Comment (JcMinarro) [inline livedata/src/test/java/io/getstream/chat/android/livedata/PaginationTest.kt:22]: Check only the `cid` doesn't cover all cases. It is assuming our `cid` will be unique, but it is something that we can't guarantee with our own models.
Apart of that, test should guarantee the full list content is the one we expect

File: livedata/src/test/java/io/getstream/chat/android/livedata/PaginationTest.kt [hunk 2]
```diff
@@ -162,6 +165,54 @@ class PaginationTest {
                     },
                     it
                 )
+            },
+            // last_updated is a computed field based on max(createdAt, lastMessageAt)
```
Comment (JcMinarro) [inline livedata/src/test/java/io/getstream/chat/android/livedata/PaginationTest.kt:169]: `last_updated` is not a field on `Channel` Wee need to add it

File: livedata/src/test/java/io/getstream/chat/android/livedata/PaginationTest.kt (hunk 1 above)
Comment (tschellenbach) [reply livedata/src/test/java/io/getstream/chat/android/livedata/PaginationTest.kt:23]: `cid` is a unique identifier for channels

File: livedata/src/test/java/io/getstream/chat/android/livedata/PaginationTest.kt (hunk 2 above)
Comment (tschellenbach) [reply livedata/src/test/java/io/getstream/chat/android/livedata/PaginationTest.kt:169]: what do you think is best? want to add a property on the low level client that computes the max(createdAt, lastMessageAt)?

Comment (tschellenbach) [reply livedata/src/test/java/io/getstream/chat/android/livedata/PaginationTest.kt:168]: i saw the other PR, nice

**Review by JcMinarro — APPROVED** [review]
